name: GitHub Actions Demo1
on:
  push:
    branches:
      - ci-test
jobs:
  demo1:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://github.com
    steps:
      - name: demo1
        run: echo 'GitHub Actions Demo1'
      - name: echo $HOGE
        run: echo $HOGE
        env:
          HOGE: ${{ github.event.deployment_status.state }}
