name: GitHub Actions Demo1
on:
  push:
    branches:
      - ci-test
jobs:
  unit-test:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://github.com
    steps:
      - name: demo1
        run: echo 'GitHub Actions Demo1'
