name: 'Deploy to Production environment'

on:
  push:
    tags:
      - '2022*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com
    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'Hello'
      - run: gdp publish -t $GITHUB_SHA
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

