name: 'Deploy to Production environment'

on:
  push:
    tags:
      - '20[0-9][0-9]*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com
    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'Hello'
