name: 'Deploy to Production environment'

on: deployment_status

jobs:
  echo-url:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'https://github.com/st1t/actions-test'
  deploy-production:
    if: |
      github.event.deployment_status.state == 'success' && 
      github.event.deployment_status.environment == 'staging'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com
    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'Hello'
