name: 'Deploy to Production environment'

on:
  deployment: 'staging'
  deployment_status: 'success'
#  push:
#    tags:
#      - '2*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com
    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'Hello'
